import { Languages } from './types';

export const EN: Languages = {
  lang: 'en',
  mainTitle: 'Main Container',
  mainGreeting: 'Hello,',
  welcomeTitle: 'Welcome Page',
  mainLink: 'Main',
  welcomeLink: 'Welcome',
  errorTitle: 'Oops!',
  errorMessageText: 'Please reload the page.',
  notFoundTitle: 'Page not found',
  notFoundText: 'Please check the URL',
  welcomeMain: 'Main Page',
  welcomeSignIn: 'Sign In',
  welcomeSignUp: 'Sign Up',
  welcomeTeamTitle: 'HAQ team',
  welcomeTeamIntro:
    'A trio of outstanding frontend experts united by their unusual approach to web development.',
  welcomeMemberName1: 'Ilya Bukhairov',
  welcomeMemberName2: 'Kamilla Agliullina',
  welcomeMemberName3: 'Aleksandr Reznikov',
  welcomeMemberRole1: 'Team Lead',
  welcomeMemberRole2: 'Developer',
  welcomeMemberRole3: 'Developer',
  welcomeProjectFactsTitle: 'Project Facts',
  welcomeProjectFactsPRs: 'Pull Requests',
  welcomeProjectFactsCommits: 'Commits',
  welcomeProjectFactsBranches: 'Branches',
  welcomeProjectFactsLines: 'Lines of code',
  welcomeBioContributionsTitle: 'Contributions',
  welcomeBioAboutTitle: 'About',
  welcomeBioLocation1: 'Tashkent, Uzbekistan',
  welcomeBioLocation2: 'Omsk, Russia',
  welcomeBioLocation3: 'Gomel, Belarus',
  welcomeBioContribution1:
    'Ilya managed the project, set tasks, reflected them in Jira cards, worked with project logic and documentation, information and error handling.',
  welcomeBioContribution2:
    'Camilla handled filling out the welcome page and validating data on the client side using Zod, outputting errors via Toastify',
  welcomeBioContribution3:
    'Alexander worked with the main logical part of the project, dealing with GraphQL window customization as well as design',
  welcomeBioAbout1:
    'Ilya started this course from stage-0 with basic knowledge of HTML/CSS, all the time he was trying to break into the top positions, he studied hard for 60 hours a week for it. At the initial stages, when there was enough time to close tasks - he was very much engaged in theory, which helped in the future in the course interviews. Ilya loves playing guitar, Dota 2 and Diablo (3-4). He also enjoys the adrenaline of high speed racing a car and setting records on a bike. In the future he really wants to become a Team Leader and make a lot of money.',
  welcomeBioAbout2:
    "Kamilla started her way to IT from Stage 0 in 2022. Before it she used to be a teacher, so changing profession too a lot of effort. Married to a software engineer, owns a horse and 2 ginger cats. She likes Vanilla js, cross-stitching and 17' laptops. In her free time she usually goes to the forest to cry out loud over ESLint function length limitation. Strongly prefers using switch(true) instead of chain of if-elses. Windows user (yet...).",
  welcomeBioAbout3:
    'Just like his colleagues, Alexander started learning JS in December last year on a basic course from RS school. Within the first two weeks he realized that frontend was what he was looking for. He dedicated about 70% of his time to learning, which allowed him to rank at the top. His work Minesweeper made it to the list of top 10 best jobs. One of the toughest assignments was Clean Code, but it was after that - he fell in love with clean code and continues to improve this skill. He loves development and wants it to be his job.',
  welcomeCollaborationTitle: 'Collaboration',
  welcomeCollaborationDescription:
    'The developers of our team met on the RSS-JS course. Ilya and Alexander immediately agreed on the cleanliness of the code and neatness of development, while Camilla took on a supporting role and the search for quick solutions. The team stayed in touch almost around the clock, responding instantly to problems arising during the development process. Every idea and subsequent solution was discussed with the entire team in advance, and no pull-request was merged without the approval of the entire team. HAQ faced various challenges during the development process, which were mostly due to the inexperience of the team members. Mentors came to the rescue immediately, who, with their impressive IT experience, were able to suggest where to look for a solution to the problem',
  welcomeThanksTitle: 'Special Thanks',
  welcomeMentorName4: 'Dmitry',
  welcomeMentorName5: 'Valeria',
  welcomeMentorName6: 'Oleg',
  welcomeMentorRole: 'Mentor',
  welcomeMentorDescription:
    "Many thanks for helping us build the app to our mentors - masters of their craft, frontend virtuosos, friendly and attentive to detail. Throughout the mentorship, they made sure to stay on top of their mentees' business. These amazing guys guided our young inexperienced team through the thorns to the stars.",
  queryEditorTitle: 'Query Editor',
  responseViewerHeader: 'Response',
  setApi: 'set Api',
  placeholderUrl: 'enter the URL...',
  loginTitle: 'Sign In',
  registerTitle: 'Sign Up',
  resetTitle: 'Reset Password',
  signOut: 'Sign Out',
  emailPlaceholder: 'E-mail Address',
  passwordPlaceholder: 'Password',
  loginButtonText: 'Login',
  registerButtonText: 'Register',
  googleButtonText: 'Login with Google',
  resetPasswordText: 'Forgot Password',
  accountPositiveText: 'Already have an account?',
  accountNegativeText: "Don't have an account?",
  accountSupportText: 'now',
  registerLink: 'Register',
  namePlaceholder: 'Name',
  resetButtonText: 'Send password reset email',
  headersButtonName: 'Headers',
  variablesButtonName: 'Variables',
  docsHeader: 'DOCS',
  emailErrorTitle: 'Wrong email',
  emailError: 'Invalid email',
  passwordErrorTitle: 'Password strength:',
  passwordErrorLength: 'Password must contain at least 8 characters',
  passwordErrorLetter: 'Password must contain at least one letter',
  passwordErrorDigital: 'Password must contain at least one digit',
  passwordErrorUppercase: 'Password must contain at least one uppercase letter',
  passwordErrorLowercase: 'Password must contain at least one lowercase letter',
  passwordErrorSpecial: 'Password must contain at least one special character',
  mainTypesHeader: 'All Schema Types',
  fieldsHeader: 'Fields',
  rootTypesHeader: 'Root Types',
  noDescription: 'Description is not available',
  undefinedItem: 'Undefined item',
  typeHeader: 'Type',
  argsHeader: 'Arguments',
  resetSent: 'Password reset link sent',
  notSchema: 'This API does not provide a schema',
  invalidVariables: 'Variables are invalid JSON:',
  invalidHeaders: 'Headers are invalid JSON:',
  forbiddenHeaders:
    'You have entered forbidden headers. More detailed: https://fetch.spec.whatwg.org/#forbidden-header-name',
};

export const RU: Languages = {
  lang: 'ru',
  mainTitle: 'Главный контейнер',
  mainGreeting: 'Здравствуй,',
  welcomeTitle: 'Давайте знакомиться!',
  mainLink: 'Главная',
  welcomeLink: 'О нас',
  errorTitle: 'Ой!',
  errorMessageText: 'Пожалуйста, перезагрузите страницу.',
  notFoundTitle: 'Страница не найдена',
  notFoundText: 'Пожалуйста, проверьте URL',
  welcomeMain: 'На главную',
  welcomeSignIn: 'Вход',
  welcomeSignUp: 'Регистрация',
  welcomeTeamTitle: 'Команда HAQ',
  welcomeTeamIntro:
    'Трио выдающихся специалистов по фронтенду, объединенных необычным подходом к веб-разработке.',
  welcomeMemberName1: 'Илья Бухаиров',
  welcomeMemberName2: 'Камилла Аглиуллина',
  welcomeMemberName3: 'Александр Резников',
  welcomeMemberRole1: 'За главного здесь',
  welcomeMemberRole2: 'Разработчик',
  welcomeMemberRole3: 'Разработчик',
  welcomeProjectFactsTitle: 'Факты о проекте',
  welcomeProjectFactsPRs: 'Пулл-реквесты',
  welcomeProjectFactsCommits: 'Коммиты',
  welcomeProjectFactsBranches: 'Ветки',
  welcomeProjectFactsLines: 'Строки кода',
  welcomeBioContributionsTitle: 'Вклад в проект',
  welcomeBioAboutTitle: 'Краткая информация',
  welcomeBioLocation1: 'Ташкент, Узбекистан',
  welcomeBioLocation2: 'Омск, Россия',
  welcomeBioLocation3: 'Гомель, Беларусь',
  welcomeBioContribution1:
    'Илья руководил проектом, ставил задачи, отражал их в карточках Jira, работал с логикой проекта и документацией, обработкой информации и ошибок',
  welcomeBioContribution2:
    'Камилла занималась заполнением страницы приветствия и валидацией данных на стороне клиента при помощи Zod, выводила ошибки через Toastify',
  welcomeBioContribution3:
    'Александр работал с основной логической частью проекта, занимаясь настройкой окна GraphQL, а также дизайном',
  welcomeBioAbout1:
    'Илья начал этот курс со Stage-0 с базовыми знаниями HTML/CSS, все это время он пытался пробиться в топ-позиции, усердно занимался по 60 часов в неделю. На начальных этапах, когда было достаточно времени на закрытие заданий - он очень много занимался теорией, что помогло в дальнейшем на собеседованиях. Илья любит играть на гитаре, в Dota 2 и Diablo (3-4). Также ему нравится получать адреналин от скоростных гонок на автомобиле и ставить рекорды на велосипеде. В будущем он очень хочет стать тим-лидом и зарабатывать много денег.',
  welcomeBioAbout2:
    'Камилла начала свой путь в IT со Stage-0 в 2022 году. До этого она была учителем, поэтому смена профессии потребовала от нее много усилий. Замужем за инженером-программистом, имеет лошадь и двух рыжих котов. Она любит Vanilla js, вышивание крестиком и 17-дюймовые ноутбуки. В свободное время она обычно ходит в лес, чтобы громко поплакать над ограничением длины функции ESLint. Предпочитает использовать switch(true) вместо цепочки if-else. Пользователь Windows (пока...).',
  welcomeBioAbout3:
    'Как и его коллеги, Александр начал изучать JS в декабре прошлого года на базовом курсе от школы RS. В течение первых двух недель он понял, что фронтенд - это то, что он искал. Он посвятил изучению около 70 % своего времени, что позволило ему занять первое место. Его работа Minesweeper попала в список 10 лучших заданий. Одним из самых сложных заданий был "Чистый код", но именно после него он полюбил чистый код и продолжает совершенствовать этот навык. Он любит разработку и хочет, чтобы она стала его работой.',
  welcomeCollaborationTitle: 'Сотрудничество',
  welcomeCollaborationDescription:
    'Разработчики нашей команды познакомились на курсе RSS-JS. Илья и Александр сразу сошлись на чистоте кода и аккуратности разработки, а Камилла взяла на себя вспомогательную роль и поиск быстрых решений. Команда оставалась на связи практически круглосуточно, мгновенно реагируя на возникающие в процессе разработки проблемы. Каждая идея и последующее решение обсуждались со всей командой заранее, и ни один pull-request не объединялся без одобрения всей команды. В процессе разработки HAQ столкнулся с различными трудностями, которые в основном были связаны с неопытностью членов команды. На помощь сразу же приходили менторы, которые, обладая внушительным опытом работы в IT, могли подсказать, в каком направлении искать решение возникшей проблемы',
  welcomeThanksTitle: 'Особое спасибо',
  welcomeMentorName4: 'Дмитрий',
  welcomeMentorName5: 'Валерия',
  welcomeMentorName6: 'Олег',
  welcomeMentorRole: 'Ментор',
  welcomeMentorDescription:
    'Большое спасибо за помощь в создании приложения нашим менторам - мастерам своего дела, виртуозам фронтенда, дружелюбным и внимательным к деталям. На протяжении всего менторства они старались быть в курсе дел своих подопечных. Эти потрясающие ребята провели нашу молодую неопытную команду через тернии к звездам.',
  queryEditorTitle: 'Редактор запросов',
  responseViewerHeader: 'Ответ',
  setApi: 'задать Api',
  placeholderUrl: 'введите URL...',
  loginTitle: 'Вход',
  registerTitle: 'Регистрация',
  resetTitle: 'Сброс пароля',
  signOut: 'Выйти',
  emailPlaceholder: 'Электронная почта',
  passwordPlaceholder: 'Пароль',
  loginButtonText: 'Войти',
  registerButtonText: 'Зарегистрироваться',
  googleButtonText: 'Войти с Google',
  resetPasswordText: 'Забыл(а) пароль',
  accountPositiveText: 'Уже есть аккаунт?',
  accountNegativeText: 'Нет аккаунта?',
  registerLink: 'Зарегистрируйтесь',
  accountSupportText: 'сейчас',
  namePlaceholder: 'Имя',
  resetButtonText: 'Запросить ссылку на сброс пароля',
  headersButtonName: 'Заголовки',
  variablesButtonName: 'Переменные',
  docsHeader: 'ДОКА',
  emailErrorTitle: 'Неправильный e-mail',
  emailError: 'Введенные данные не являются e-mail адресом',
  passwordErrorTitle: 'Сила пароля:',
  passwordErrorLength: 'Длина пароля не должна быть менее 8 символов',
  passwordErrorLetter: 'Пароль должен содержать букву',
  passwordErrorDigital: 'Пароль должен содержать число',
  passwordErrorUppercase: 'Пароль должен содержать заглавную букву',
  passwordErrorLowercase: 'Пароль должен содержать строчную букву',
  passwordErrorSpecial: 'Пароль должен содержать специальный символ',
  mainTypesHeader: 'Все типы схемы',
  fieldsHeader: 'Поля',
  rootTypesHeader: 'Корневые типы',
  noDescription: 'Описание отсутствует',
  undefinedItem: 'Неизвестный элемент',
  typeHeader: 'Тип',
  argsHeader: 'Аргументы',
  resetSent: 'Ссылка для сброса пароля отправлена',
  notSchema: 'Эта АПИ не предоставляет схему',
  invalidVariables: 'Переменные не соответствуют формату JSON:',
  invalidHeaders: 'Заголовки не соответствуют формату JSON:',
  forbiddenHeaders:
    'Вы ввели запрещенные заголовки. Подробнее: https://fetch.spec.whatwg.org/#forbidden-header-name',
};
