import { Languages } from './types';

export const EN: Languages = {
  lang: 'en',
  mainTitle: 'Main Container',
  mainGreeting: 'Hello,',
  welcomeTitle: 'Welcome Page',
  mainLink: 'Main',
  welcomeLink: 'Welcome',
  errorTitle: 'Oops!',
  errorMessageText: 'Please reload the page.',
  notFoundTitle: 'Page not found',
  notFoundText: 'please check the URL',
  loginTitle: 'SignIn',
  registerTitle: 'SignUp',
  resetTitle: 'Reset Password',
  signOut: 'Sign Out',
  emailPlaceholder: 'E-mail Address',
  passwordPlaceholder: 'Password',
  loginButtonText: 'Login',
  registerButtonText: 'Register',
  googleButtonText: 'Login with Google',
  resetPasswordText: 'Forgot Password',
  accountPositiveText: 'Already have an account?',
  accountNegativeText: "Don't have an account?",
  accountSupportText: 'now.',
  registerLink: 'Register',
  namePlaceholder: 'Name',
  resetButtonText: 'Send password reset email',
};

export const RU: Languages = {
  lang: 'ru',
  mainTitle: 'Главный контейнер',
  mainGreeting: 'Здравствуй,',
  welcomeTitle: 'Страница приветствия',
  mainLink: 'Главная',
  welcomeLink: 'Приветствие',
  errorTitle: 'Ой!',
  errorMessageText: 'Пожалуйста перезагрузите страницу.',
  notFoundTitle: 'Страница не найдена',
  notFoundText: 'проверьте пожалуйста URL',
  loginTitle: 'Вход',
  registerTitle: 'Регистрация',
  resetTitle: 'Сброс пароля',
  signOut: 'Выйти',
  emailPlaceholder: 'Электронная почта',
  passwordPlaceholder: 'Пароль',
  loginButtonText: 'Войти',
  registerButtonText: 'Зарегистрироваться',
  googleButtonText: 'Войти с Google',
  resetPasswordText: 'Забыл(а) пароль',
  accountPositiveText: 'Уже есть аккаунт?',
  accountNegativeText: 'Нет аккаунта?',
  registerLink: 'Зарегистрируйтесь',
  accountSupportText: 'сейчас.',
  namePlaceholder: 'Имя',
  resetButtonText: 'Запросить ссылку на сброс пароля',
};
